import type {
  AnimationDescriptor,
  AnimationPreset,
} from "./types";

/**
 * Catalog registry. In 5.2 the reveal family is implemented (CSS engine);
 * the remaining presets are declared (vocabulary) and marked implemented:false
 * so the runtime degrades them to a safe static render until 5.3 fills them in.
 */
export const ANIMATION_REGISTRY: Record<AnimationPreset, AnimationDescriptor> = {
  none: {
    preset: "none",
    label: "Sin animación",
    description: "El módulo aparece estático.",
    category: "entrance",
    engine: "none",
    cost: "low",
    implemented: true,
    recommendedDuration: 0,
    reducedMotionSafe: true,
  },
  "soft-reveal": {
    preset: "soft-reveal",
    label: "Aparición suave",
    description: "Fundido con un desplazamiento mínimo hacia arriba.",
    category: "entrance",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "fade-up": {
    preset: "fade-up",
    label: "Fade hacia arriba",
    description: "Aparece desplazándose desde abajo.",
    category: "scroll",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "fade-down": {
    preset: "fade-down",
    label: "Fade hacia abajo",
    description: "Aparece desplazándose desde arriba.",
    category: "scroll",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "soft-scale": {
    preset: "soft-scale",
    label: "Escala suave",
    description: "Aparece con un ligero acercamiento.",
    category: "scroll",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "slide-left": {
    preset: "slide-left",
    label: "Deslizar desde la derecha",
    description: "Entra deslizándose desde la derecha.",
    category: "scroll",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "slide-right": {
    preset: "slide-right",
    label: "Deslizar desde la izquierda",
    description: "Entra deslizándose desde la izquierda.",
    category: "scroll",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "blur-focus": {
    preset: "blur-focus",
    label: "Desenfoque a foco",
    description: "Pasa de desenfocado a nítido.",
    category: "scroll",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.7,
    reducedMotionSafe: true,
  },

  "rotate-in": {
    preset: "rotate-in",
    label: "Rotación sutil",
    description: "Entra con una ligera rotación y ascenso.",
    category: "scroll",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.7,
    reducedMotionSafe: true,
  },
  "section-lift": {
    preset: "section-lift",
    label: "Elevación de sección",
    description: "La sección se eleva con una escala mínima.",
    category: "scroll",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.7,
    reducedMotionSafe: true,
  },
  "editorial-reveal": {
    preset: "editorial-reveal",
    label: "Revelado editorial",
    description: "Ascenso elegante con leve variación de escala.",
    category: "entrance",
    engine: "css",
    cost: "low",
    implemented: true,
    recommendedDuration: 0.8,
    reducedMotionSafe: true,
  },
  "curtain-reveal": {
    preset: "curtain-reveal",
    label: "Revelado cortina",
    description: "Se descubre progresivamente con una máscara vertical.",
    category: "entrance",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.8,
    reducedMotionSafe: true,
  },
  "image-clip": {
    preset: "image-clip",
    label: "Revelado con recorte",
    description: "Se descubre horizontalmente con una máscara.",
    category: "composed",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.8,
    reducedMotionSafe: true,
  },
  "stagger-children": {
    preset: "stagger-children",
    label: "Hijos escalonados",
    description: "Los elementos internos aparecen en secuencia.",
    category: "composed",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "text-rise": {
    preset: "text-rise",
    label: "Texto asciende",
    description: "Las palabras suben y aparecen en secuencia.",
    category: "text",
    engine: "motion",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  "masked-text": {
    preset: "masked-text",
    label: "Texto enmascarado",
    description: "Las palabras se descubren tras una máscara.",
    category: "text",
    engine: "motion",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  },
  floating: {
    preset: "floating",
    label: "Flotación",
    description: "Ornamentos que flotan suavemente.",
    category: "decoration",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 6,
    reducedMotionSafe: true,
  },
  "ambient-gradient": {
    preset: "ambient-gradient",
    label: "Gradiente ambiental",
    description: "Fondo con gradiente que se desplaza lentamente.",
    category: "decoration",
    engine: "css",
    cost: "moderate",
    implemented: true,
    recommendedDuration: 12,
    reducedMotionSafe: true,
  },
  sparkle: {
    preset: "sparkle",
    label: "Destellos",
    description: "Pequeños destellos sutiles.",
    category: "decoration",
    engine: "css",
    cost: "high",
    implemented: true,
    recommendedDuration: 3,
    reducedMotionSafe: true,
  },

  // --- Declarados, no implementados aún (compuestos/de módulo → 5.4) --------
  "layered-reveal": stub("layered-reveal", "Revelado por capas", "entrance", "moderate"),
  "welcome-entrance": stub("welcome-entrance", "Entrada de bienvenida", "entrance", "moderate"),
  "line-draw": stub("line-draw", "Trazo de línea", "text", "moderate"),
  "ornamental-drift": stub("ornamental-drift", "Deriva ornamental", "decoration", "high"),
};

function stub(
  preset: AnimationPreset,
  label: string,
  category: AnimationDescriptor["category"],
  cost: AnimationDescriptor["cost"],
): AnimationDescriptor {
  return {
    preset,
    label,
    description: "Disponible próximamente.",
    category,
    engine: "none",
    cost,
    implemented: false,
    recommendedDuration: 0.6,
    reducedMotionSafe: true,
  };
}

/** Presets rendered by the CSS reveal engine (AnimatedModule-compatible). */
export const CSS_REVEAL_PRESETS = new Set<AnimationPreset>([
  "soft-reveal",
  "fade-up",
  "fade-down",
  "soft-scale",
  "slide-left",
  "slide-right",
  "blur-focus",
  "rotate-in",
  "section-lift",
  "editorial-reveal",
  "curtain-reveal",
  "image-clip",
]);

export function isImplemented(preset: AnimationPreset): boolean {
  return ANIMATION_REGISTRY[preset]?.implemented ?? false;
}
